version: '3.8'

services:
  vtb-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vtb-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # For browser access, use the actual server IP/domain (update this!)
      - NEXT_PUBLIC_API_URL=${PUBLIC_API_URL:-http://localhost:8081}
      - NEXT_PUBLIC_APP_URL=${PUBLIC_APP_URL:-http://localhost:3000}
      - NEXT_PUBLIC_ENV=production
      # For server-side rendering, use Docker network name
      - API_URL_INTERNAL=http://api-gateway:8081
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    name: app-network
    external: true  # Assumes the backend network already exists